const types = {
  POST_SCHOOLS_DETAILS_REQUESTED: 'POST_SCHOOLS_DETAILS_REQUESTED',
  POST_SCHOOLS_DETAILS_SUCCESS: 'POST_SCHOOLS_DETAILS_SUCCESS',
  POST_SCHOOLS_DETAILS_FAILURE: 'POST_SCHOOLS_DETAILS_FAILURE',
  REMEMBER_ME: 'REMEMBER_ME',
  FORGETLINK_REQUEST: 'FORGETLINK_REQUEST',
  FORGETLINK_SUCCESS: 'FORGETLINK_SUCCESS',
  FORGETLINK_FAILED: 'FORGETLINK_FAILED',
  FORGETOTP_REQUEST: 'FORGETOTP_REQUEST',
  FORGETOTP_SUCCESS: 'FORGETOTP_SUCCESS',
  FORGETOTP_FAILED: 'FORGETOTP_FAILED',
  RESETPASSWORD_REQUEST: 'RESETPASSWORD_REQUEST',
  RESETPASSWORD_SUCCESS: 'RESETPASSWORD_SUCCESS',
  RESETPASSWORD_FAILED: 'RESETPASSWORD_FAILED',
  VALIDATE_TOKEN_REQUEST: 'VALIDATE_TOKEN_REQUEST',
  VALIDATE_TOKEN_SUCCESS: 'VALIDATE_TOKEN_SUCCESS',
  VALIDATE_TOKEN_FAILED: 'VALIDATE_TOKEN_FAILED',
  VALIDATE_AUTH_TOKEN_REQUEST: 'VALIDATE_AUTH_TOKEN_REQUEST',
  VALIDATE_AUTH_TOKEN_SUCCESS: 'VALIDATE_AUTH_TOKEN_SUCCESS',
  VALIDATE_AUTH_TOKEN_FAILED: 'VALIDATE_AUTH_TOKEN_FAILED',
  LOGOUT: 'LOGOUT',
};

export default types;
