const types = {
  POST_SUPPORTER_REQUEST: 'POST_SUPPORTER_REQUEST',
  POST_SUPPORTER_SUCCESS: 'POST_SUPPORTER_SUCCESS',
  POST_SUPPORTER_FAILED: 'POST_SUPPORTER_FAILED',

  GET_PROJECTS_REQUEST: 'GET_PROJECTS_REQUEST',
  GET_PROJECTS_SUCCESS: 'GET_PROJECTS_SUCCESS',
  GET_PROJECTS_FAILED: 'GET_PROJECTS_FAILED',
  RESET_MESSAGES: 'RESET_MESSAGES',
};
export default types;
